version: "3.9"
services:
    video_chat:
        image: postgres:latest
        ports:
            - 5434:5432
        env_file:
            - .dockerenv
        volumes:
            - video_chat_data:/var/lib/postgresql/data

volumes:
    video_chat_data:
